### ISSUE TITLE
Error during Torsion - Torsion did not reach target dihedral angle! 

### ISSUE THREAD

**Issue by jacekkozuch** [TinkerTools/poltype2#25]
I am getting an error during torsion refinement, because a torsion didn't reach it's target (see below). That's definitely something "new", i.e. since the introduction of XTB. I remember that before there was an "IF" that just ignored such occasions.

Below find a link to the zipped folder and an excerpt of the error message.
Thx in advance!
Jacek

 
https://1drv.ms/u/s!ApPMvraeXGN3hLJeJRm69hTmpASV8w?e=bJMCmV

> ...
> Traceback (most recent call last):
>   File "/home/jkozuch/poltype2/PoltypeModules/poltype.py", line 7994, in RunPoltype
>     poltype.main()
>   File "/home/jkozuch/poltype2/PoltypeModules/poltype.py", line 3522, in main
>     params= self.GenerateParameters()
>   File "/home/jkozuch/poltype2/PoltypeModules/poltype.py", line 4911, in GenerateParameters
>     torgen.gen_torsion(self,optmol,self.torsionrestraint,mol)
>   File "/home/jkozuch/poltype2/PoltypeModules/torsiongenerator.py", line 1154, in gen_torsion
>     CheckIfQMOptReachedTargetDihedral(poltype,cartxyz,initialtinkerstructure,torset,optmol,variabletorlist,phaseangles) # QM usually freezes dof but xtb and ANI does not freeze so need to add check now.
>   File "/home/jkozuch/poltype2/PoltypeModules/torsiongenerator.py", line 781, in CheckIfQMOptReachedTargetDihedral
>     raise ValueError(string)
> ValueError: Torsion did not reach target dihedral angle! torsion = [9, 11, 20, 21] tinker minimized dihedral angle is 167.8661215925513 but the optimized dihedral angle is at 176.5357700064363, tinker structure is oCNFbocDep-opt-1-3-115_preQMOPTprefit_xyzformat.xyz , opt strucuture is xtb-opt-1-3-115.xyz
> ...

**Comment by jacekkozuch** [comment]
Hey,

**Comment by jacekkozuch** [comment]
BTW I just looked once more into it, and seems to be still my previous problem due to the nitrile. I will close this open issue and write once more in my previous one.
