### ISSUE TITLE
Polytype2 error when running with addhydrogens = True

### ISSUE THREAD

**Issue by seanwangsalad** [TinkerTools/poltype2#54]
Dear developers,

I am trying to parameterize a protonated guanidium compound. I fed the program an unprotonated compound and specified:
structure=guanidio.mol2
addhydrogens = True

However, when I have the "addhydrogens = True" flag, poltype gets hung and I see this being outputted in the .log:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/mypoltype2/bin/psi4", line 369, in <module>
  File "/opt/anaconda3/envs/mypoltype2/bin/psi4", line 369, in <module>
Traceback (most recent call last):
    content = psi4.process_input(content)
    content = psi4.process_input(content)
  File "/opt/anaconda3/envs/mypoltype2/bin/psi4", line 369, in <module>
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/mypoltype2/lib/python3.12/site-packages/psi4/driver/inputparser.py", line 702, in process_input
  File "/opt/anaconda3/envs/mypoltype2/lib/python3.12/site-packages/psi4/driver/inputparser.py", line 702, in process_input
Traceback (most recent call last):
  File "/opt/anaconda3/envs/mypoltype2/bin/psi4", line 369, in <module>
    content = psi4.process_input(content)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/mypoltype2/lib/python3.12/site-packages/psi4/driver/inputparser.py", line 702, in process_input
    content = psi4.process_input(content)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/mypoltype2/lib/python3.12/site-packages/psi4/driver/inputparser.py", line 702, in process_input
    temp = re.sub(memory_string, process_memory_command, temp)
    temp = re.sub(memory_string, process_memory_command, temp)
    temp = re.sub(memory_string, process_memory_command, temp)
    temp = re.sub(memory_string, process_memory_command, temp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/mypoltype2/lib/python3.12/re/__init__.py", line 186, in sub
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/mypoltype2/lib/python3.12/re/__init__.py", line 186, in sub
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/mypoltype2/lib/python3.12/re/__init__.py", line 186, in sub
  File "/opt/anaconda3/envs/mypoltype2/lib/python3.12/re/__init__.py", line 186, in sub
    return _compile(pattern, flags).sub(repl, string, count)
    return _compile(pattern, flags).sub(repl, string, count)
    return _compile(pattern, flags).sub(repl, string, count)
    return _compile(pattern, flags).sub(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/mypoltype2/lib/python3.12/site-packages/psi4/driver/inputparser.py", line 258, in process_memory_command
  File "/opt/anaconda3/envs/mypoltype2/lib/python3.12/site-packages/psi4/driver/inputparser.py", line 258, in process_memory_command
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/mypoltype2/lib/python3.12/site-packages/psi4/driver/inputparser.py", line 258, in process_memory_command
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/mypoltype2/lib/python3.12/site-packages/psi4/driver/inputparser.py", line 258, in process_memory_command
    mem_in_bytes = set_memory(sig + units, execute=False)
    mem_in_bytes = set_memory(sig + units, execute=False)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    mem_in_bytes = set_memory(sig + units, execute=False)
    mem_in_bytes = set_memory(sig + units, execute=False)
  File "/opt/anaconda3/envs/mypoltype2/lib/python3.12/site-packages/psi4/driver/p4util/util.py", line 218, in set_memory
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/mypoltype2/lib/python3.12/site-packages/psi4/driver/p4util/util.py", line 218, in set_memory
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/mypoltype2/lib/python3.12/site-packages/psi4/driver/p4util/util.py", line 218, in set_memory
  File "/opt/anaconda3/envs/mypoltype2/lib/python3.12/site-packages/psi4/driver/p4util/util.py", line 218, in set_memory
    raise ValidationError(
    raise ValidationError(
psi4.driver.p4util.exceptions.ValidationError: set_memory(): Requested 0.0 MiB (0.0 MB); minimum 250 MiB (263 MB). Please, sir, I want some more.
psi4.driver.p4util.exceptions.ValidationError: set_memory(): Requested 0.0 MiB (0.0 MB); minimum 250 MiB (263 MB). Please, sir, I want some more.
    raise ValidationError(
    raise ValidationError(
psi4.driver.p4util.exceptions.ValidationError: set_memory(): Requested 0.0 MiB (0.0 MB); minimum 250 MiB (263 MB). Please, sir, I want some more.
psi4.driver.p4util.exceptions.ValidationError: set_memory(): Requested 0.0 MiB (0.0 MB); minimum 250 MiB (263 MB). Please, sir, I want some more.

**Comment by seanwangsalad** [comment]
Found a way to workaround:
I took the Ionization_state_0.mol structure that was outputted and ran that again but repalcing addhydrogens = True with addhydrogentocharged = False in the .ini file. That seemed to have worked
